version: "3.8"
services:
  ytapi:
    container_name: youtube_api
    image: node:lts-alpine
    command: sh -c "npm install && npm start"
    volumes:
      - ./:/var/www 
    ports:
      - "3061:3061"
    working_dir: /var/www
